title: 要么中，要么串
email: ihuanglimin@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  姿势分享，Angular,Vue,React,TypeScript...
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.ihuanglimin.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hlm_mlh
github_username:  DesignHhuang

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

